import '../models/food_item.dart';

final List<FoodItem> dummyMenu = [
  // Snacks
  FoodItem(
    id: 's1',
    name: 'Samosa',
    price: 15,
    imageUrl: 'assets/images/samosa.jpeg',
    category: 'Snacks',
    description: 'Crispy fried snack with spicy potato filling.',
    isVeg: true,
  ),
  FoodItem(
    id: 's2',
    name: 'French Fries',
    price: 40,
    imageUrl: 'assets/images/fries.jpeg',
    category: 'Snacks',
    description: 'Golden and crispy fried potato sticks.',
    isVeg: true,
  ),
  FoodItem(
    id: 's3',
    name: 'Bread Pakora',
    price: 20,
    imageUrl: 'assets/images/bread_pakora.jpeg',
    category: 'Snacks',
    description: 'Spiced potato-filled bread fritters.',
    isVeg: true,
  ),
  FoodItem(
    id: 's4',
    name: 'Burger',
    price: 40,
    imageUrl: 'assets/images/burger.jpeg',
    category: 'Snacks',
    description: 'Soft bun with patty, veggies, and sauces.',
    isVeg: true,
  ),
  FoodItem(
    id: 's5',
    name: 'Pizza',
    price: 70,
    imageUrl: 'assets/images/pizza.jpg',
    category: 'Snacks',
    description: 'Cheesy pizza with mixed toppings.',
    isVeg: false,
  ),
  FoodItem(
    id: 's6',
    name: 'Chowmein',
    price: 80,
    imageUrl: 'assets/images/chowmein.jpg',
    category: 'Snacks',
    description: 'Stir-fried noodles with vegetables.',
    isVeg: true,
  ),
  FoodItem(
    id: 's7',
    name: 'Spring Roll',
    price: 90,
    imageUrl: 'assets/images/spring_roll.jpg',
    category: 'Snacks',
    description: 'Crispy rolls stuffed with vegetables.',
    isVeg: true,
  ),
  FoodItem(
    id: 's8',
    name: 'Sandwich',
    price: 60,
    imageUrl: 'assets/images/sandwich.jpeg',
    category: 'Snacks',
    description: 'Bread sandwich with veggie or cheese filling.',
    isVeg: true,
  ),
  FoodItem(
    id: 's9',
    name: 'Vada Pav',
    price: 20,
    imageUrl: 'assets/images/vada_pav.png',
    category: 'Snacks',
    description: 'Spicy potato fritter in a bun.',
    isVeg: true,
  ),

  // Main Course
  FoodItem(
    id: 'm1',
    name: 'Veg Thali',
    price: 70,
    imageUrl: 'assets/images/veg_thali.jpg',
    category: 'Main Course',
    description: 'Complete vegetarian meal with curry, rice, and roti.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm2',
    name: 'Chhole Bhature',
    price: 60,
    imageUrl: 'assets/images/chhole_bhature.jpg',
    category: 'Main Course',
    description: 'Spicy chickpeas served with deep-fried bread.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm3',
    name: 'Aloo Puri',
    price: 50,
    imageUrl: 'assets/images/aloo_poori.jpg',
    category: 'Main Course',
    description: 'Spiced potato curry served with fried puris.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm4',
    name: 'Rajma Chawal',
    price: 50,
    imageUrl: 'assets/images/rajma_chawal.jpg',
    category: 'Main Course',
    description: 'Red kidney beans curry with steamed rice.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm5',
    name: 'Kadi Chawal',
    price: 90,
    imageUrl: 'assets/images/kadi_chawal.jpeg',
    category: 'Main Course',
    description: 'Yogurt-based curry with rice.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm6',
    name: 'Idli Sambhar',
    price: 50,
    imageUrl: 'assets/images/idli_sambhar.jpeg',
    category: 'Main Course',
    description: 'Steamed rice cakes served with lentil soup.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm7',
    name: 'Dosa Sambhar',
    price: 70,
    imageUrl: 'assets/images/dosa_sambhar.jpg',
    category: 'Main Course',
    description: 'Crispy crepe with lentil soup and chutneys.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm8',
    name: 'Chhole Naan',
    price: 70,
    imageUrl: 'assets/images/chhole_naan.jpg',
    category: 'Main Course',
    description: 'Spicy chickpeas with soft naan bread.',
    isVeg: true,
  ),
  FoodItem(
    id: 'm9',
    name: 'Dal Tandoori Roti',
    price: 80,
    imageUrl: 'assets/images/dal_roti.jpg',
    category: 'Main Course',
    description: 'Lentil curry served with tandoori roti.',
    isVeg: true,
  ),

  // Beverages
  FoodItem(
    id: 'b1',
    name: 'Cold Coffee',
    price: 35,
    imageUrl: 'assets/images/cold_coffee.jpeg',
    category: 'Beverages',
    description: 'Chilled coffee with milk and ice.',
    isVeg: true,
  ),
  FoodItem(
    id: 'b2',
    name: 'Lemonade',
    price: 20,
    imageUrl: 'assets/images/lemonade.jpg',
    category: 'Beverages',
    description: 'Refreshing lemon drink.',
    isVeg: true,
  ),
  FoodItem(
    id: 'b3',
    name: 'Badam Shake',
    price: 50,
    imageUrl: 'assets/images/badam_shake.jpg',
    category: 'Beverages',
    description: 'Almond flavored milk shake.',
    isVeg: true,
  ),
  FoodItem(
    id: 'b4',
    name: 'Hot Coffee',
    price: 20,
    imageUrl: 'assets/images/coffee.jpg',
    category: 'Beverages',
    description: 'Carbonated soft drink.',
    isVeg: true,
  ),
  FoodItem(
    id: 'b5',
    name: 'Lassi',
    price: 50,
    imageUrl: 'assets/images/lassi.jpg',
    category: 'Beverages',
    description: 'Traditional yogurt-based drink.',
    isVeg: true,
  ),
  FoodItem(
    id: 'b6',
    name: 'Jal Jeera',
    price: 30,
    imageUrl: 'assets/images/jal_jeera.jpeg',
    category: 'Beverages',
    description: 'Spicy tangy cumin-flavored drink.',
    isVeg: true,
  ),
];
